/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerName = IDL.Text;
export const ServiceType = IDL.Variant({
  'plumber' : IDL.Null,
  'cleaning' : IDL.Null,
  'electrician' : IDL.Null,
  'acRepair' : IDL.Null,
  'carpenter' : IDL.Null,
});
export const PreferredDate = IDL.Text;
export const Address = IDL.Text;
export const Time = IDL.Int;
export const PhoneNo = IDL.Text;
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : CustomerName,
  'serviceType' : ServiceType,
  'preferredDate' : PreferredDate,
  'address' : Address,
  'requestTime' : Time,
  'phoneNo' : PhoneNo,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], []),
  'submitBooking' : IDL.Func(
      [CustomerName, PhoneNo, ServiceType, PreferredDate, Address],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerName = IDL.Text;
  const ServiceType = IDL.Variant({
    'plumber' : IDL.Null,
    'cleaning' : IDL.Null,
    'electrician' : IDL.Null,
    'acRepair' : IDL.Null,
    'carpenter' : IDL.Null,
  });
  const PreferredDate = IDL.Text;
  const Address = IDL.Text;
  const Time = IDL.Int;
  const PhoneNo = IDL.Text;
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : CustomerName,
    'serviceType' : ServiceType,
    'preferredDate' : PreferredDate,
    'address' : Address,
    'requestTime' : Time,
    'phoneNo' : PhoneNo,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], []),
    'submitBooking' : IDL.Func(
        [CustomerName, PhoneNo, ServiceType, PreferredDate, Address],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };